parameters:
#    zeega_editor.example.class: Zeega\EditorBundle\Example

services:
#    zeega_editor.example:
#        class: %zeega_editor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
