parameters:
#    zeega_discovery.example.class: Zeega\DiscoveryBundle\Example

services:
#    zeega_discovery.example:
#        class: %zeega_discovery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
