parameters:
#    zeega_bookmarklet.example.class: Zeega\BookmarkletBundle\Example

services:
#    zeega_bookmarklet.example:
#        class: %zeega_bookmarklet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
