parameters:
#    zeega_community.example.class: Zeega\CommunityBundle\Example

services:
#    zeega_community.example:
#        class: %zeega_community.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
